### ISSUE TITLE
dex_imdb_wiki.caffemodel.pt

### ISSUE THREAD

**Issue by LHL921026** [InterDigitalInc/HRFAE#17]
Hi, I would like to train the model, but I had the problem when convert the caffe model to pt file. Is that possible to provide the dex_imdb_wiki.caffemodel.pt file for me?

**Comment by quleileileilei** [comment]
could you please provide the dex_imdb_wiki.caffemodel.pt?

**Comment by AOguo21** [comment]
> could you please provide the dex_imdb_wiki.caffemodel.pt?
I have this file but I'm not sure if it's correct, I can send it to you if you need it.
