### ISSUE TITLE
how to get faces of children

### ISSUE THREAD

**Issue by blue-butterfly** [InterDigitalInc/HRFAE#2]
Thanks for your work very much.
there is a question that: when I test the pics prepared, i set '--target_age 5' , it can not generate faces of chilren well ?

**Comment by Xu-Yao** [comment]
Hi blue-butterfly. As mentioned in the paper, we only consider age transformation in the age range {20, . . . , 69}. This is a limitation due to the pretrained age classifier, which yields less accurate age estimation for faces of people younger than 20 years old or much older than 65 years old.

**Comment by blue-butterfly** [comment]
Got it, Thanks very much
~~and thanks for sharing the great work again.
