### ISSUE TITLE
ResolvePackageNotFound: - openssl==1.1.1=h7b6447c_0

### ISSUE THREAD

**Issue by ghost** [InterDigitalInc/HRFAE#7]
While trying to create a virtual environment using the steps mentioned in [README.md](https://github.com/InterDigitalInc/HRFAE/blob/master/README.md) , I faced this issue:

`ResolvePackageNotFound: - openssl==1.1.1=h7b6447c_0`

Did anyone face a similar issue?

**Comment by ghost** [comment]
This [solution](https://github.com/datitran/object_detector_app/issues/41#issuecomment-357825469) solved this issue.

But I fail to understand why this happened? Anyone know? @Xu-Yao

**Comment by junhocho** [comment]
Can you specify how you solve this problem? 
I am also struggling with this issue
`ResolvePackageNotFound: - openssl==1.1.1=h7b6447c_0`

**Comment by gautamsreekumar** [comment]
@junhocho I faced this issue with another repository. I changed the line ```- openssl==1.1.1=h7b6447c_0``` to ```- openssl==1.1.1```.
